apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-sso-exporter
  namespace: $(kubernetes-namespace)
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(aws-account-id):role/aws-sso-exporter # replace with actual account id
    eks.amazonaws.com/sts-regional-endpoints: "true"